version: "3.8"

services:
  mariadb:
    image: mariadb:10.5
    secrets:
      - mariadb_user
      - mariadb_password
      - mariadb_root_password
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER_FILE: /run/secrets/mariadb_user
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb_root_password
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:6.4.3-php8.1-apache
    secrets:
      - mariadb_user
      - mariadb_password
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER_FILE: /run/secrets/mariadb_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mariadb_password
    ports:
      - "8081:80"
    depends_on:
      - mariadb

secrets:
  mariadb_user:
    file: ./secrets/mariadb_user.txt
  mariadb_password:
    file: ./secrets/mariadb_password.txt
  mariadb_root_password:
    file: ./secrets/mariadb_root_password.txt



