apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o k8s/
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - env:
            - name: MARIADB_DATABASE
              value: wordpress
            - name: MARIADB_PASSWORD_FILE
              value: /run/secrets/mariadb-password
            - name: MARIADB_ROOT_PASSWORD_FILE
              value: /run/secrets/mariadb-root-password
            - name: MARIADB_USER_FILE
              value: /run/secrets/mariadb-user
          image: mariadb:10.5
          name: mariadb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: mariadb-user
              subPath: mariadb-user
            - mountPath: /run/secrets
              name: mariadb-password
              subPath: mariadb-password
            - mountPath: /run/secrets
              name: mariadb-root-password
              subPath: mariadb-root-password
      restartPolicy: Always
      volumes:
        - name: mariadb-user
          secret:
            items:
              - key: mariadb-user
                path: mariadb-user
            secretName: mariadb-user
        - name: mariadb-password
          secret:
            items:
              - key: mariadb-password
                path: mariadb-password
            secretName: mariadb-password
        - name: mariadb-root-password
          secret:
            items:
              - key: mariadb-root-password
                path: mariadb-root-password
            secretName: mariadb-root-password
